version: '3.9'
services:
  postgres:
    image: postgres:16
    container_name: hlr-postgres
    environment:
      POSTGRES_DB: hlrdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Interview@2025
    ports:
      - "5432:5432"
    volumes:
      - hlr_pg_data:/var/lib/postgresql/data

volumes:
  hlr_pg_data:
